/*CREATE TABLE USUARIO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    ADMIN BOOLEAN NOT NULL
);

CREATE TABLE CLIENTE (
    ID BIGINT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    APELLIDOS VARCHAR(255) NOT NULL,
    TELEFONO VARCHAR(255) NOT NULL,
    DIRECCION VARCHAR(255) NOT NULL,
    NUMERO_TARJETA VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    CONSTRAINT FK_CLIENTE_USUARIO FOREIGN KEY (ID) REFERENCES USUARIO (ID)
);

CREATE TABLE CATEGORIA (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    DESTACADA BOOLEAN NOT NULL,
    IMAGEN VARCHAR(255) NOT NULL
);

CREATE TABLE PRODUCTO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    PVP FLOAT NOT NULL,
    DESCUENTO FLOAT NOT NULL,
    IMAGEN VARCHAR(255) NOT NULL,
    CATEGORIA_ID BIGINT,
    CONSTRAINT FK_PRODUCTO_CATEGORIA FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA(ID)
);

